require: rubocop-rspec
Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
Metrics/LineLength:
  Enabled: false
Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'db/**/*'
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1
